AWSTemplateFormatVersion: '2010-09-09'
Description: >
  VPC with one public and one private subnet. Public subnet has Internet access via IGW. DNS support enabled. No NAT.

Parameters:

  VpcCidr:
    Type: String
    Default: 11.200.123.0/24
    Description: The IPv4 CIDR block for the VPC

  PrivateSubnetCidr:
    Type: String
    Default: 11.200.123.0/25
    Description: CIDR block for the private subnet

  PublicSubnetCidr:
    Type: String
    Default: 11.200.123.128/25
    Description: CIDR block for the public subnet

  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: The Availability Zone to deploy the subnets into

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: network-bootcamp-vpc-cfn

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: {}

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCidr
      AvailabilityZone: !Ref AvailabilityZone
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: network-bootcamp-public-subnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCidr
      AvailabilityZone: !Ref AvailabilityZone
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: network-bootcamp-private-subnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: network-bootcamp-public-rt

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: network-bootcamp-private-rt

  PublicSubnetRouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnetRouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

Outputs:

  VPCID:
    Description: VPC ID
    Value: !Ref VPC

  PublicSubnetID:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet

  PrivateSubnetID:
    Description: Private Subnet ID
    Value: !Ref PrivateSubnet

  IGWID:
    Description: Internet Gateway ID
    Value: !Ref InternetGateway
